import pandas as pd




df = pd.read_csv('./tester.csv')

print(df.info())
df.rename({'SYMBOL \n': 'SYMBOL', 'COMPANY \n': 'COMPANY','NAME OF THE ACQUIRER/DISPOSER \n':'NAME OF THE ACQUIRER/DISPOSER','CATEGORY OF PERSON \n':'CATEGORY OF PERSON','% SHAREHOLDING (PRIOR) \n':'% SHAREHOLDING (PRIOR)','NO. OF SECURITIES (ACQUIRED/DISPLOSED) \n':'NO. OF SECURITIES (ACQUIRED/DISPLOSED)', 'VALUE OF SECURITY (ACQUIRED/DISPLOSED) \n':'VALUE OF SECURITY (ACQUIRED/DISPLOSED)','ACQUISITION/DISPOSAL TRANSACTION TYPE \n':'ACQUISITION/DISPOSAL TRANSACTION TYPE','TYPE OF SECURITY (POST) \n':'TYPE OF SECURITY (POST)', 'NO. OF SECURITY (POST) \n':'NO. OF SECURITY (POST)','MODE OF ACQUISITION \n':'MODE OF ACQUISITION','BROADCASTE DATE AND TIME \n':'BROADCASTE DATE AND TIME'}, axis=1, inplace=True)

print(df.info())